### ISSUE TITLE
Adapter is not yet ported to preCICE v3

### ISSUE THREAD

**Issue by tapegoji** [precice/elmer-adapter#3]
I followed the isntructions of how to compile it. However, I faced an issue with it. Have you seen this error?

`../Coupler_Solver.so: undefined symbol: precicef_is_action_required_

**Comment by tapegoji** [comment]
It seems that this is not being updated for v3. How can I help in this? need guidance.

**Comment by uekerman** [comment]
Yes, the adapter has not yet been ported to v3. Any help in this direction is highly appreciated.

There is a [porting guide](https://precice.org/couple-your-code-porting-v2-3.html), focusing on the C++ API. You can follow this guide for Fortran pretty much as well. For the exact names of the functions, have a look at the [source code](https://github.com/precice/precice/blob/main/extras/bindings/fortran/include/precice/preciceFortran.hpp).

I would recommend opening a draft PR early and ask for help there if you run into issues.

**Comment by tapegoji** [comment]
Hey, I was able to successfully port it. However, I needed to do a lot of changes. Let me know what you think.

**Comment by fsimonis** [comment]
Closed by https://github.com/precice/elmer-adapter/pull/4
